window.portfolioData = {
  "works": [
    {
      "id": "work003",
      "title": "유명한아이 - Ride or Die",
      "majorCategory": "production",
      "minorCategory": "musicvideo",
      "date": "2025",
      "role": "Director, Editor",
      "featured": false,
      "youtubeUrl": "https://youtu.be/zNexk1f8McE?si=UqSf18rOJqo7BUv5",
      "description": "",
      "thumbnail": "images/works/work003/thumb.jpg",
      "stills": [
        "images/works/work003/still1.jpg",
        "images/works/work003/still2.jpg",
        "images/works/work003/still3.jpg",
        "images/works/work003/still4.jpg",
        "images/works/work003/still5.jpg",
        "images/works/work003/still6.jpg",
        "images/works/work003/still7.jpg",
        "images/works/work003/still8.jpg",
        "images/works/work003/still9.jpg",
        "images/works/work003/still10.jpg",
        "images/works/work003/still11.jpg",
        "images/works/work003/still12.jpg",
        "images/works/work003/still13.jpg",
        "images/works/work003/still14.jpg",
        "images/works/work003/still15.jpg",
        "images/works/work003/still16.jpg",
        "images/works/work003/still17.jpg",
        "images/works/work003/still18.jpg",
        "images/works/work003/still19.jpg",
        "images/works/work003/still20.jpg",
        "images/works/work003/still21.jpg",
        "images/works/work003/still22.jpg",
        "images/works/work003/still23.jpg",
        "images/works/work003/still24.jpg",
        "images/works/work003/still25.jpg",
        "images/works/work003/still26.jpg"
      ],
      "credits": {
        "client": "",
        "director": "신형준",
        "cinematographer": "정다빈",
        "lighting": "김형민",
        "editor": "신형준"
      },
      "_originalIndex": 0
    },
    {
      "id": "work002",
      "title": "유명한아이 - Master card",
      "majorCategory": "production",
      "minorCategory": "musicvideo",
      "date": "2025",
      "role": "Director, Editor",
      "featured": false,
      "youtubeUrl": "https://youtu.be/FWiJjxwFq2w?si=RwVmeo-tJGSzePAu",
      "description": "",
      "thumbnail": "images/works/work002/thumb.png",
      "stills": [
        "images/works/work002/still1.png",
        "images/works/work002/still2.png",
        "images/works/work002/still3.png",
        "images/works/work002/still4.png",
        "images/works/work002/still5.png",
        "images/works/work002/still6.png",
        "images/works/work002/still7.png",
        "images/works/work002/still8.png",
        "images/works/work002/still9.png",
        "images/works/work002/still10.png",
        "images/works/work002/still11.png",
        "images/works/work002/still12.png",
        "images/works/work002/still13.png",
        "images/works/work002/still14.png",
        "images/works/work002/still15.png",
        "images/works/work002/still16.png",
        "images/works/work002/still17.png",
        "images/works/work002/still18.png"
      ],
      "credits": {
        "client": "",
        "director": "신형준",
        "cinematographer": "정다빈",
        "lighting": "정준혁",
        "editor": "신형준"
      },
      "_originalIndex": 1
    },
    {
      "id": "work001",
      "title": "다농바이오 브랜드필름",
      "majorCategory": "production",
      "minorCategory": "commercial",
      "date": "2024-05",
      "role": "Director, Editor",
      "featured": false,
      "youtubeUrl": "https://youtu.be/hQyXen5-dY8?si=nKO-JnbAWWBS6A3I",
      "description": "",
      "thumbnail": "images/works/work001/thumb.jpg",
      "stills": [
        "images/works/work001/still1.png",
        "images/works/work001/still2.png",
        "images/works/work001/still3.png",
        "images/works/work001/still4.png",
        "images/works/work001/still5.png",
        "images/works/work001/still6.png",
        "images/works/work001/still7.png",
        "images/works/work001/still8.png",
        "images/works/work001/still9.png",
        "images/works/work001/still10.png",
        "images/works/work001/still11.png",
        "images/works/work001/still12.png",
        "images/works/work001/still13.png",
        "images/works/work001/still14.png"
      ],
      "credits": [
        { "role": "Client", "name": "다농바이오" },
        { "role": "Director", "name": "신형준" },
        { "role": "DOP", "name": "정다빈" },
        { "role": "Color", "name": "신형준" }
      ],
      "_originalIndex": 2
    }
  ]
};