window.portfolioData = {
  "works": [
    {
      "id": "work005",
      "title": "다농바이오 DANONG BIO - '풍류' 행사 영상 스케치",
      "majorCategory": "production",
      "minorCategory": "etc",
      "date": "2024",
      "role": "product , edit",
      "featured": false,
      "youtubeUrl": "https://youtu.be/iMKmkhE91eU?si=G7qP-0uAJmharvAJ",
      "description": "",
      "thumbnail": "images/works/work005/thumb.png",
      "stills": [
        "images/works/work005/still1.png",
        "images/works/work005/still2.png",
        "images/works/work005/still3.png",
        "images/works/work005/still4.png",
        "images/works/work005/still5.png",
        "images/works/work005/still6.png",
        "images/works/work005/still7.png",
        "images/works/work005/still8.png",
        "images/works/work005/still9.png",
        "images/works/work005/still10.png",
        "images/works/work005/still11.png",
        "images/works/work005/still12.png",
        "images/works/work005/still13.png",
        "images/works/work005/still14.png",
        "images/works/work005/still15.png",
        "images/works/work005/still16.png",
        "images/works/work005/still17.png",
        "images/works/work005/still18.png",
        "images/works/work005/still19.png",
        "images/works/work005/still20.png",
        "images/works/work005/still21.png",
        "images/works/work005/still22.png"
      ],
      "credits": [
        {
          "role": "a film by",
          "name": "LOOKUP MEDIA"
        }
      ],
      "_originalIndex": 0
    },
    {
      "id": "work004",
      "title": "이자카야 산쥬로쿠 홍보영상",
      "majorCategory": "production",
      "minorCategory": "etc",
      "date": "2025",
      "role": "product / direct / edit",
      "featured": false,
      "youtubeUrl": "https://youtube.com/shorts/cFpCfgA204Y",
      "description": "",
      "thumbnail": "images/works/work004/thumb.png",
      "stills": [],
      "credits": [
        {
          "role": "a film by",
          "name": "LOOKUP MEDIA"
        }
      ],
      "_originalIndex": 1
    },
    {
      "id": "work003",
      "title": "유명한아이 - Ride or Die",
      "majorCategory": "production",
      "minorCategory": "musicvideo",
      "date": "2025",
      "featured": false,
      "youtubeUrl": "https://youtu.be/zNexk1f8McE?si=UqSf18rOJqo7BUv5",
      "description": "",
      "thumbnail": "images/works/work003/thumb.jpg",
      "stills": [
        "images/works/work003/still1.jpg",
        "images/works/work003/still2.jpg",
        "images/works/work003/still3.jpg",
        "images/works/work003/still4.jpg",
        "images/works/work003/still5.jpg",
        "images/works/work003/still6.jpg",
        "images/works/work003/still7.jpg",
        "images/works/work003/still8.jpg",
        "images/works/work003/still9.jpg",
        "images/works/work003/still10.jpg",
        "images/works/work003/still11.jpg",
        "images/works/work003/still12.jpg",
        "images/works/work003/still13.jpg",
        "images/works/work003/still14.jpg",
        "images/works/work003/still15.jpg",
        "images/works/work003/still16.jpg",
        "images/works/work003/still17.jpg",
        "images/works/work003/still18.jpg",
        "images/works/work003/still19.jpg",
        "images/works/work003/still20.jpg",
        "images/works/work003/still21.jpg",
        "images/works/work003/still22.jpg",
        "images/works/work003/still23.jpg",
        "images/works/work003/still24.jpg",
        "images/works/work003/still25.jpg",
        "images/works/work003/still26.jpg"
      ],
      "credits": {
        "client": "",
        "director": "신형준",
        "cinematographer": "정다빈",
        "lighting": "김형민",
        "editor": "신형준"
      },
      "_originalIndex": 2,
      "role": "Director, Editor"
    },
    {
      "id": "work002",
      "title": "유명한아이 - Master card",
      "majorCategory": "production",
      "minorCategory": "musicvideo",
      "date": "2025",
      "featured": false,
      "youtubeUrl": "https://youtu.be/FWiJjxwFq2w?si=RwVmeo-tJGSzePAu",
      "description": "",
      "thumbnail": "images/works/work002/thumb.png",
      "stills": [
        "images/works/work002/still1.png",
        "images/works/work002/still2.png",
        "images/works/work002/still3.png",
        "images/works/work002/still4.png",
        "images/works/work002/still5.png",
        "images/works/work002/still6.png",
        "images/works/work002/still7.png",
        "images/works/work002/still8.png",
        "images/works/work002/still9.png",
        "images/works/work002/still10.png",
        "images/works/work002/still11.png",
        "images/works/work002/still12.png",
        "images/works/work002/still13.png",
        "images/works/work002/still14.png",
        "images/works/work002/still15.png",
        "images/works/work002/still16.png",
        "images/works/work002/still17.png",
        "images/works/work002/still18.png"
      ],
      "credits": {
        "client": "",
        "director": "신형준",
        "cinematographer": "정다빈",
        "lighting": "정준혁",
        "editor": "신형준"
      },
      "_originalIndex": 3,
      "role": "Director, Editor"
    },
    {
      "id": "work001",
      "title": "다농바이오 브랜드필름",
      "majorCategory": "production",
      "minorCategory": "commercial",
      "date": "2024-05",
      "featured": false,
      "youtubeUrl": "https://youtu.be/hQyXen5-dY8?si=nKO-JnbAWWBS6A3I",
      "description": "",
      "thumbnail": "images/works/work001/thumb.jpg",
      "stills": [
        "images/works/work001/still1.png",
        "images/works/work001/still2.png",
        "images/works/work001/still3.png",
        "images/works/work001/still4.png",
        "images/works/work001/still5.png",
        "images/works/work001/still6.png",
        "images/works/work001/still7.png",
        "images/works/work001/still8.png",
        "images/works/work001/still9.png",
        "images/works/work001/still10.png",
        "images/works/work001/still11.png",
        "images/works/work001/still12.png",
        "images/works/work001/still13.png",
        "images/works/work001/still14.png"
      ],
      "credits": {
        "client": "다농바이오",
        "director": "신형준",
        "cinematographer": "정다빈",
        "lighting": "임진우",
        "editor": "신형준"
      },
      "_originalIndex": 4,
      "role": "Director, Editor"
    }
  ]
};