UPDATE works SET thumbnail_key = 'works/work027/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work027' AND thumbnail_key = 'images/works/work027/thumb.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/001.webp' WHERE work_id = 'work027' AND sort_order = 0 AND image_key = 'images/works/work027/still1.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/002.webp' WHERE work_id = 'work027' AND sort_order = 1 AND image_key = 'images/works/work027/still2.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/003.webp' WHERE work_id = 'work027' AND sort_order = 2 AND image_key = 'images/works/work027/still3.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/004.webp' WHERE work_id = 'work027' AND sort_order = 3 AND image_key = 'images/works/work027/still4.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/005.webp' WHERE work_id = 'work027' AND sort_order = 4 AND image_key = 'images/works/work027/still5.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/006.webp' WHERE work_id = 'work027' AND sort_order = 5 AND image_key = 'images/works/work027/still6.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/007.webp' WHERE work_id = 'work027' AND sort_order = 6 AND image_key = 'images/works/work027/still7.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/008.webp' WHERE work_id = 'work027' AND sort_order = 7 AND image_key = 'images/works/work027/still8.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/009.webp' WHERE work_id = 'work027' AND sort_order = 8 AND image_key = 'images/works/work027/still9.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/010.webp' WHERE work_id = 'work027' AND sort_order = 9 AND image_key = 'images/works/work027/still10.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/011.webp' WHERE work_id = 'work027' AND sort_order = 10 AND image_key = 'images/works/work027/still11.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/012.webp' WHERE work_id = 'work027' AND sort_order = 11 AND image_key = 'images/works/work027/still12.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/013.webp' WHERE work_id = 'work027' AND sort_order = 12 AND image_key = 'images/works/work027/still13.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/014.webp' WHERE work_id = 'work027' AND sort_order = 13 AND image_key = 'images/works/work027/still14.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/015.webp' WHERE work_id = 'work027' AND sort_order = 14 AND image_key = 'images/works/work027/still15.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/016.webp' WHERE work_id = 'work027' AND sort_order = 15 AND image_key = 'images/works/work027/still16.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/017.webp' WHERE work_id = 'work027' AND sort_order = 16 AND image_key = 'images/works/work027/still17.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/018.webp' WHERE work_id = 'work027' AND sort_order = 17 AND image_key = 'images/works/work027/still18.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/019.webp' WHERE work_id = 'work027' AND sort_order = 18 AND image_key = 'images/works/work027/still19.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/020.webp' WHERE work_id = 'work027' AND sort_order = 19 AND image_key = 'images/works/work027/still20.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/021.webp' WHERE work_id = 'work027' AND sort_order = 20 AND image_key = 'images/works/work027/still21.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/022.webp' WHERE work_id = 'work027' AND sort_order = 21 AND image_key = 'images/works/work027/still22.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/023.webp' WHERE work_id = 'work027' AND sort_order = 22 AND image_key = 'images/works/work027/still23.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/024.webp' WHERE work_id = 'work027' AND sort_order = 23 AND image_key = 'images/works/work027/still24.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/025.webp' WHERE work_id = 'work027' AND sort_order = 24 AND image_key = 'images/works/work027/still25.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/026.webp' WHERE work_id = 'work027' AND sort_order = 25 AND image_key = 'images/works/work027/still26.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/027.webp' WHERE work_id = 'work027' AND sort_order = 26 AND image_key = 'images/works/work027/still27.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/028.webp' WHERE work_id = 'work027' AND sort_order = 27 AND image_key = 'images/works/work027/still28.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/029.webp' WHERE work_id = 'work027' AND sort_order = 28 AND image_key = 'images/works/work027/still29.jpg';
UPDATE work_images SET image_key = 'works/work027/stills/030.webp' WHERE work_id = 'work027' AND sort_order = 29 AND image_key = 'images/works/work027/still30.jpg';
UPDATE works SET thumbnail_key = 'works/work026/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work026' AND thumbnail_key = 'images/works/work026/thumb.jpg';
UPDATE work_images SET image_key = 'works/work026/stills/001.webp' WHERE work_id = 'work026' AND sort_order = 0 AND image_key = 'images/works/work026/still1.jpg';
UPDATE work_images SET image_key = 'works/work026/stills/002.webp' WHERE work_id = 'work026' AND sort_order = 1 AND image_key = 'images/works/work026/still2.jpg';
UPDATE work_images SET image_key = 'works/work026/stills/003.webp' WHERE work_id = 'work026' AND sort_order = 2 AND image_key = 'images/works/work026/still3.jpg';
UPDATE work_images SET image_key = 'works/work026/stills/004.webp' WHERE work_id = 'work026' AND sort_order = 3 AND image_key = 'images/works/work026/still4.jpg';
UPDATE work_images SET image_key = 'works/work026/stills/005.webp' WHERE work_id = 'work026' AND sort_order = 4 AND image_key = 'images/works/work026/still5.jpg';
UPDATE work_images SET image_key = 'works/work026/stills/006.webp' WHERE work_id = 'work026' AND sort_order = 5 AND image_key = 'images/works/work026/still6.jpg';
UPDATE work_images SET image_key = 'works/work026/stills/007.webp' WHERE work_id = 'work026' AND sort_order = 6 AND image_key = 'images/works/work026/still7.jpg';
UPDATE work_images SET image_key = 'works/work026/stills/008.webp' WHERE work_id = 'work026' AND sort_order = 7 AND image_key = 'images/works/work026/still8.jpg';
UPDATE work_images SET image_key = 'works/work026/stills/009.webp' WHERE work_id = 'work026' AND sort_order = 8 AND image_key = 'images/works/work026/still9.jpg';
UPDATE work_images SET image_key = 'works/work026/stills/010.webp' WHERE work_id = 'work026' AND sort_order = 9 AND image_key = 'images/works/work026/still10.jpg';
UPDATE work_images SET image_key = 'works/work026/stills/011.webp' WHERE work_id = 'work026' AND sort_order = 10 AND image_key = 'images/works/work026/still11.jpg';
UPDATE work_images SET image_key = 'works/work026/stills/012.webp' WHERE work_id = 'work026' AND sort_order = 11 AND image_key = 'images/works/work026/still12.jpg';
UPDATE work_images SET image_key = 'works/work026/stills/013.webp' WHERE work_id = 'work026' AND sort_order = 12 AND image_key = 'images/works/work026/still13.jpg';
UPDATE work_images SET image_key = 'works/work026/stills/014.webp' WHERE work_id = 'work026' AND sort_order = 13 AND image_key = 'images/works/work026/still14.jpg';
UPDATE work_images SET image_key = 'works/work026/stills/015.webp' WHERE work_id = 'work026' AND sort_order = 14 AND image_key = 'images/works/work026/still15.jpg';
UPDATE work_images SET image_key = 'works/work026/stills/016.webp' WHERE work_id = 'work026' AND sort_order = 15 AND image_key = 'images/works/work026/still16.jpg';
UPDATE works SET thumbnail_key = 'works/work025/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work025' AND thumbnail_key = 'images/works/work025/thumb.jpg';
UPDATE work_images SET image_key = 'works/work025/stills/001.webp' WHERE work_id = 'work025' AND sort_order = 0 AND image_key = 'images/works/work025/still1.jpg';
UPDATE work_images SET image_key = 'works/work025/stills/002.webp' WHERE work_id = 'work025' AND sort_order = 1 AND image_key = 'images/works/work025/still2.jpg';
UPDATE work_images SET image_key = 'works/work025/stills/003.webp' WHERE work_id = 'work025' AND sort_order = 2 AND image_key = 'images/works/work025/still3.jpg';
UPDATE work_images SET image_key = 'works/work025/stills/004.webp' WHERE work_id = 'work025' AND sort_order = 3 AND image_key = 'images/works/work025/still4.jpg';
UPDATE work_images SET image_key = 'works/work025/stills/005.webp' WHERE work_id = 'work025' AND sort_order = 4 AND image_key = 'images/works/work025/still5.jpg';
UPDATE work_images SET image_key = 'works/work025/stills/006.webp' WHERE work_id = 'work025' AND sort_order = 5 AND image_key = 'images/works/work025/still6.jpg';
UPDATE work_images SET image_key = 'works/work025/stills/007.webp' WHERE work_id = 'work025' AND sort_order = 6 AND image_key = 'images/works/work025/still7.jpg';
UPDATE work_images SET image_key = 'works/work025/stills/008.webp' WHERE work_id = 'work025' AND sort_order = 7 AND image_key = 'images/works/work025/still8.jpg';
UPDATE work_images SET image_key = 'works/work025/stills/009.webp' WHERE work_id = 'work025' AND sort_order = 8 AND image_key = 'images/works/work025/still9.jpg';
UPDATE work_images SET image_key = 'works/work025/stills/010.webp' WHERE work_id = 'work025' AND sort_order = 9 AND image_key = 'images/works/work025/still10.jpg';
UPDATE work_images SET image_key = 'works/work025/stills/011.webp' WHERE work_id = 'work025' AND sort_order = 10 AND image_key = 'images/works/work025/still11.jpg';
UPDATE work_images SET image_key = 'works/work025/stills/012.webp' WHERE work_id = 'work025' AND sort_order = 11 AND image_key = 'images/works/work025/still12.jpg';
UPDATE work_images SET image_key = 'works/work025/stills/013.webp' WHERE work_id = 'work025' AND sort_order = 12 AND image_key = 'images/works/work025/still13.jpg';
UPDATE work_images SET image_key = 'works/work025/stills/014.webp' WHERE work_id = 'work025' AND sort_order = 13 AND image_key = 'images/works/work025/still14.jpg';
UPDATE work_images SET image_key = 'works/work025/stills/015.webp' WHERE work_id = 'work025' AND sort_order = 14 AND image_key = 'images/works/work025/still15.jpg';
UPDATE work_images SET image_key = 'works/work025/stills/016.webp' WHERE work_id = 'work025' AND sort_order = 15 AND image_key = 'images/works/work025/still16.jpg';
UPDATE work_images SET image_key = 'works/work025/stills/017.webp' WHERE work_id = 'work025' AND sort_order = 16 AND image_key = 'images/works/work025/still17.jpg';
UPDATE works SET thumbnail_key = 'works/work024/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work024' AND thumbnail_key = 'images/works/work024/thumb.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/001.webp' WHERE work_id = 'work024' AND sort_order = 0 AND image_key = 'images/works/work024/still1.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/002.webp' WHERE work_id = 'work024' AND sort_order = 1 AND image_key = 'images/works/work024/still2.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/003.webp' WHERE work_id = 'work024' AND sort_order = 2 AND image_key = 'images/works/work024/still3.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/004.webp' WHERE work_id = 'work024' AND sort_order = 3 AND image_key = 'images/works/work024/still4.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/005.webp' WHERE work_id = 'work024' AND sort_order = 4 AND image_key = 'images/works/work024/still5.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/006.webp' WHERE work_id = 'work024' AND sort_order = 5 AND image_key = 'images/works/work024/still6.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/007.webp' WHERE work_id = 'work024' AND sort_order = 6 AND image_key = 'images/works/work024/still7.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/008.webp' WHERE work_id = 'work024' AND sort_order = 7 AND image_key = 'images/works/work024/still8.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/009.webp' WHERE work_id = 'work024' AND sort_order = 8 AND image_key = 'images/works/work024/still9.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/010.webp' WHERE work_id = 'work024' AND sort_order = 9 AND image_key = 'images/works/work024/still10.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/011.webp' WHERE work_id = 'work024' AND sort_order = 10 AND image_key = 'images/works/work024/still11.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/012.webp' WHERE work_id = 'work024' AND sort_order = 11 AND image_key = 'images/works/work024/still12.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/013.webp' WHERE work_id = 'work024' AND sort_order = 12 AND image_key = 'images/works/work024/still13.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/014.webp' WHERE work_id = 'work024' AND sort_order = 13 AND image_key = 'images/works/work024/still14.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/015.webp' WHERE work_id = 'work024' AND sort_order = 14 AND image_key = 'images/works/work024/still15.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/016.webp' WHERE work_id = 'work024' AND sort_order = 15 AND image_key = 'images/works/work024/still16.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/017.webp' WHERE work_id = 'work024' AND sort_order = 16 AND image_key = 'images/works/work024/still17.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/018.webp' WHERE work_id = 'work024' AND sort_order = 17 AND image_key = 'images/works/work024/still18.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/019.webp' WHERE work_id = 'work024' AND sort_order = 18 AND image_key = 'images/works/work024/still19.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/020.webp' WHERE work_id = 'work024' AND sort_order = 19 AND image_key = 'images/works/work024/still20.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/021.webp' WHERE work_id = 'work024' AND sort_order = 20 AND image_key = 'images/works/work024/still21.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/022.webp' WHERE work_id = 'work024' AND sort_order = 21 AND image_key = 'images/works/work024/still22.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/023.webp' WHERE work_id = 'work024' AND sort_order = 22 AND image_key = 'images/works/work024/still23.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/024.webp' WHERE work_id = 'work024' AND sort_order = 23 AND image_key = 'images/works/work024/still24.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/025.webp' WHERE work_id = 'work024' AND sort_order = 24 AND image_key = 'images/works/work024/still25.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/026.webp' WHERE work_id = 'work024' AND sort_order = 25 AND image_key = 'images/works/work024/still26.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/027.webp' WHERE work_id = 'work024' AND sort_order = 26 AND image_key = 'images/works/work024/still27.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/028.webp' WHERE work_id = 'work024' AND sort_order = 27 AND image_key = 'images/works/work024/still28.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/029.webp' WHERE work_id = 'work024' AND sort_order = 28 AND image_key = 'images/works/work024/still29.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/030.webp' WHERE work_id = 'work024' AND sort_order = 29 AND image_key = 'images/works/work024/still30.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/031.webp' WHERE work_id = 'work024' AND sort_order = 30 AND image_key = 'images/works/work024/still31.jpg';
UPDATE work_images SET image_key = 'works/work024/stills/032.webp' WHERE work_id = 'work024' AND sort_order = 31 AND image_key = 'images/works/work024/still32.jpg';
UPDATE works SET thumbnail_key = 'works/work023/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work023' AND thumbnail_key = 'images/works/work023/thumb.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/001.webp' WHERE work_id = 'work023' AND sort_order = 0 AND image_key = 'images/works/work023/still1.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/002.webp' WHERE work_id = 'work023' AND sort_order = 1 AND image_key = 'images/works/work023/still2.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/003.webp' WHERE work_id = 'work023' AND sort_order = 2 AND image_key = 'images/works/work023/still3.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/004.webp' WHERE work_id = 'work023' AND sort_order = 3 AND image_key = 'images/works/work023/still4.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/005.webp' WHERE work_id = 'work023' AND sort_order = 4 AND image_key = 'images/works/work023/still5.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/006.webp' WHERE work_id = 'work023' AND sort_order = 5 AND image_key = 'images/works/work023/still6.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/007.webp' WHERE work_id = 'work023' AND sort_order = 6 AND image_key = 'images/works/work023/still7.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/008.webp' WHERE work_id = 'work023' AND sort_order = 7 AND image_key = 'images/works/work023/still8.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/009.webp' WHERE work_id = 'work023' AND sort_order = 8 AND image_key = 'images/works/work023/still9.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/010.webp' WHERE work_id = 'work023' AND sort_order = 9 AND image_key = 'images/works/work023/still10.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/011.webp' WHERE work_id = 'work023' AND sort_order = 10 AND image_key = 'images/works/work023/still11.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/012.webp' WHERE work_id = 'work023' AND sort_order = 11 AND image_key = 'images/works/work023/still12.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/013.webp' WHERE work_id = 'work023' AND sort_order = 12 AND image_key = 'images/works/work023/still13.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/014.webp' WHERE work_id = 'work023' AND sort_order = 13 AND image_key = 'images/works/work023/still14.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/015.webp' WHERE work_id = 'work023' AND sort_order = 14 AND image_key = 'images/works/work023/still15.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/016.webp' WHERE work_id = 'work023' AND sort_order = 15 AND image_key = 'images/works/work023/still16.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/017.webp' WHERE work_id = 'work023' AND sort_order = 16 AND image_key = 'images/works/work023/still17.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/018.webp' WHERE work_id = 'work023' AND sort_order = 17 AND image_key = 'images/works/work023/still18.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/019.webp' WHERE work_id = 'work023' AND sort_order = 18 AND image_key = 'images/works/work023/still19.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/020.webp' WHERE work_id = 'work023' AND sort_order = 19 AND image_key = 'images/works/work023/still20.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/021.webp' WHERE work_id = 'work023' AND sort_order = 20 AND image_key = 'images/works/work023/still21.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/022.webp' WHERE work_id = 'work023' AND sort_order = 21 AND image_key = 'images/works/work023/still22.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/023.webp' WHERE work_id = 'work023' AND sort_order = 22 AND image_key = 'images/works/work023/still23.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/024.webp' WHERE work_id = 'work023' AND sort_order = 23 AND image_key = 'images/works/work023/still24.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/025.webp' WHERE work_id = 'work023' AND sort_order = 24 AND image_key = 'images/works/work023/still25.jpg';
UPDATE work_images SET image_key = 'works/work023/stills/026.webp' WHERE work_id = 'work023' AND sort_order = 25 AND image_key = 'images/works/work023/still26.jpg';
UPDATE works SET thumbnail_key = 'works/work022/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work022' AND thumbnail_key = 'images/works/work022/thumb.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/001.webp' WHERE work_id = 'work022' AND sort_order = 0 AND image_key = 'images/works/work022/still1.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/002.webp' WHERE work_id = 'work022' AND sort_order = 1 AND image_key = 'images/works/work022/still2.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/003.webp' WHERE work_id = 'work022' AND sort_order = 2 AND image_key = 'images/works/work022/still3.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/004.webp' WHERE work_id = 'work022' AND sort_order = 3 AND image_key = 'images/works/work022/still4.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/005.webp' WHERE work_id = 'work022' AND sort_order = 4 AND image_key = 'images/works/work022/still5.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/006.webp' WHERE work_id = 'work022' AND sort_order = 5 AND image_key = 'images/works/work022/still6.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/007.webp' WHERE work_id = 'work022' AND sort_order = 6 AND image_key = 'images/works/work022/still7.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/008.webp' WHERE work_id = 'work022' AND sort_order = 7 AND image_key = 'images/works/work022/still8.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/009.webp' WHERE work_id = 'work022' AND sort_order = 8 AND image_key = 'images/works/work022/still9.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/010.webp' WHERE work_id = 'work022' AND sort_order = 9 AND image_key = 'images/works/work022/still10.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/011.webp' WHERE work_id = 'work022' AND sort_order = 10 AND image_key = 'images/works/work022/still11.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/012.webp' WHERE work_id = 'work022' AND sort_order = 11 AND image_key = 'images/works/work022/still12.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/013.webp' WHERE work_id = 'work022' AND sort_order = 12 AND image_key = 'images/works/work022/still13.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/014.webp' WHERE work_id = 'work022' AND sort_order = 13 AND image_key = 'images/works/work022/still14.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/015.webp' WHERE work_id = 'work022' AND sort_order = 14 AND image_key = 'images/works/work022/still15.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/016.webp' WHERE work_id = 'work022' AND sort_order = 15 AND image_key = 'images/works/work022/still16.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/017.webp' WHERE work_id = 'work022' AND sort_order = 16 AND image_key = 'images/works/work022/still17.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/018.webp' WHERE work_id = 'work022' AND sort_order = 17 AND image_key = 'images/works/work022/still18.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/019.webp' WHERE work_id = 'work022' AND sort_order = 18 AND image_key = 'images/works/work022/still19.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/020.webp' WHERE work_id = 'work022' AND sort_order = 19 AND image_key = 'images/works/work022/still20.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/021.webp' WHERE work_id = 'work022' AND sort_order = 20 AND image_key = 'images/works/work022/still21.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/022.webp' WHERE work_id = 'work022' AND sort_order = 21 AND image_key = 'images/works/work022/still22.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/023.webp' WHERE work_id = 'work022' AND sort_order = 22 AND image_key = 'images/works/work022/still23.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/024.webp' WHERE work_id = 'work022' AND sort_order = 23 AND image_key = 'images/works/work022/still24.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/025.webp' WHERE work_id = 'work022' AND sort_order = 24 AND image_key = 'images/works/work022/still25.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/026.webp' WHERE work_id = 'work022' AND sort_order = 25 AND image_key = 'images/works/work022/still26.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/027.webp' WHERE work_id = 'work022' AND sort_order = 26 AND image_key = 'images/works/work022/still27.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/028.webp' WHERE work_id = 'work022' AND sort_order = 27 AND image_key = 'images/works/work022/still28.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/029.webp' WHERE work_id = 'work022' AND sort_order = 28 AND image_key = 'images/works/work022/still29.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/030.webp' WHERE work_id = 'work022' AND sort_order = 29 AND image_key = 'images/works/work022/still30.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/031.webp' WHERE work_id = 'work022' AND sort_order = 30 AND image_key = 'images/works/work022/still31.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/032.webp' WHERE work_id = 'work022' AND sort_order = 31 AND image_key = 'images/works/work022/still32.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/033.webp' WHERE work_id = 'work022' AND sort_order = 32 AND image_key = 'images/works/work022/still33.jpg';
UPDATE work_images SET image_key = 'works/work022/stills/034.webp' WHERE work_id = 'work022' AND sort_order = 33 AND image_key = 'images/works/work022/still34.jpg';
UPDATE works SET thumbnail_key = 'works/work021/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work021' AND thumbnail_key = 'images/works/work021/thumb.jpg';
UPDATE work_images SET image_key = 'works/work021/stills/001.webp' WHERE work_id = 'work021' AND sort_order = 0 AND image_key = 'images/works/work021/still1.jpg';
UPDATE work_images SET image_key = 'works/work021/stills/002.webp' WHERE work_id = 'work021' AND sort_order = 1 AND image_key = 'images/works/work021/still2.jpg';
UPDATE work_images SET image_key = 'works/work021/stills/003.webp' WHERE work_id = 'work021' AND sort_order = 2 AND image_key = 'images/works/work021/still3.jpg';
UPDATE work_images SET image_key = 'works/work021/stills/004.webp' WHERE work_id = 'work021' AND sort_order = 3 AND image_key = 'images/works/work021/still4.jpg';
UPDATE work_images SET image_key = 'works/work021/stills/005.webp' WHERE work_id = 'work021' AND sort_order = 4 AND image_key = 'images/works/work021/still5.jpg';
UPDATE work_images SET image_key = 'works/work021/stills/006.webp' WHERE work_id = 'work021' AND sort_order = 5 AND image_key = 'images/works/work021/still6.jpg';
UPDATE work_images SET image_key = 'works/work021/stills/007.webp' WHERE work_id = 'work021' AND sort_order = 6 AND image_key = 'images/works/work021/still7.jpg';
UPDATE work_images SET image_key = 'works/work021/stills/008.webp' WHERE work_id = 'work021' AND sort_order = 7 AND image_key = 'images/works/work021/still8.jpg';
UPDATE work_images SET image_key = 'works/work021/stills/009.webp' WHERE work_id = 'work021' AND sort_order = 8 AND image_key = 'images/works/work021/still9.jpg';
UPDATE work_images SET image_key = 'works/work021/stills/010.webp' WHERE work_id = 'work021' AND sort_order = 9 AND image_key = 'images/works/work021/still10.jpg';
UPDATE work_images SET image_key = 'works/work021/stills/011.webp' WHERE work_id = 'work021' AND sort_order = 10 AND image_key = 'images/works/work021/still11.jpg';
UPDATE work_images SET image_key = 'works/work021/stills/012.webp' WHERE work_id = 'work021' AND sort_order = 11 AND image_key = 'images/works/work021/still12.jpg';
UPDATE work_images SET image_key = 'works/work021/stills/013.webp' WHERE work_id = 'work021' AND sort_order = 12 AND image_key = 'images/works/work021/still13.jpg';
UPDATE work_images SET image_key = 'works/work021/stills/014.webp' WHERE work_id = 'work021' AND sort_order = 13 AND image_key = 'images/works/work021/still14.jpg';
UPDATE works SET thumbnail_key = 'works/work018/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work018' AND thumbnail_key = 'images/works/work018/thumb.jpg';
UPDATE work_images SET image_key = 'works/work018/stills/001.webp' WHERE work_id = 'work018' AND sort_order = 0 AND image_key = 'images/works/work018/still1.jpg';
UPDATE work_images SET image_key = 'works/work018/stills/002.webp' WHERE work_id = 'work018' AND sort_order = 1 AND image_key = 'images/works/work018/still2.jpg';
UPDATE work_images SET image_key = 'works/work018/stills/003.webp' WHERE work_id = 'work018' AND sort_order = 2 AND image_key = 'images/works/work018/still3.jpg';
UPDATE work_images SET image_key = 'works/work018/stills/006.webp' WHERE work_id = 'work018' AND sort_order = 5 AND image_key = 'images/works/work018/still6.jpg';
UPDATE work_images SET image_key = 'works/work018/stills/007.webp' WHERE work_id = 'work018' AND sort_order = 6 AND image_key = 'images/works/work018/still7.jpg';
UPDATE work_images SET image_key = 'works/work018/stills/008.webp' WHERE work_id = 'work018' AND sort_order = 7 AND image_key = 'images/works/work018/still8.jpg';
UPDATE work_images SET image_key = 'works/work018/stills/009.webp' WHERE work_id = 'work018' AND sort_order = 8 AND image_key = 'images/works/work018/still9.jpg';
UPDATE work_images SET image_key = 'works/work018/stills/010.webp' WHERE work_id = 'work018' AND sort_order = 9 AND image_key = 'images/works/work018/still10.jpg';
UPDATE work_images SET image_key = 'works/work018/stills/011.webp' WHERE work_id = 'work018' AND sort_order = 10 AND image_key = 'images/works/work018/still11.jpg';
UPDATE work_images SET image_key = 'works/work018/stills/012.webp' WHERE work_id = 'work018' AND sort_order = 11 AND image_key = 'images/works/work018/still12.jpg';
UPDATE work_images SET image_key = 'works/work018/stills/013.webp' WHERE work_id = 'work018' AND sort_order = 12 AND image_key = 'images/works/work018/still13.jpg';
UPDATE work_images SET image_key = 'works/work018/stills/014.webp' WHERE work_id = 'work018' AND sort_order = 13 AND image_key = 'images/works/work018/still14.jpg';
UPDATE work_images SET image_key = 'works/work018/stills/015.webp' WHERE work_id = 'work018' AND sort_order = 14 AND image_key = 'images/works/work018/still15.jpg';
UPDATE work_images SET image_key = 'works/work018/stills/016.webp' WHERE work_id = 'work018' AND sort_order = 15 AND image_key = 'images/works/work018/still16.jpg';
UPDATE work_images SET image_key = 'works/work018/stills/017.webp' WHERE work_id = 'work018' AND sort_order = 16 AND image_key = 'images/works/work018/still17.jpg';
UPDATE work_images SET image_key = 'works/work018/stills/018.webp' WHERE work_id = 'work018' AND sort_order = 17 AND image_key = 'images/works/work018/still18.jpg';
UPDATE work_images SET image_key = 'works/work018/stills/019.webp' WHERE work_id = 'work018' AND sort_order = 18 AND image_key = 'images/works/work018/still19.jpg';
UPDATE work_images SET image_key = 'works/work018/stills/020.webp' WHERE work_id = 'work018' AND sort_order = 19 AND image_key = 'images/works/work018/still20.jpg';
UPDATE work_images SET image_key = 'works/work018/stills/021.webp' WHERE work_id = 'work018' AND sort_order = 20 AND image_key = 'images/works/work018/still21.jpg';
UPDATE works SET thumbnail_key = 'works/work020/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work020' AND thumbnail_key = 'images/works/work020/thumb.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/001.webp' WHERE work_id = 'work020' AND sort_order = 0 AND image_key = 'images/works/work020/still1.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/002.webp' WHERE work_id = 'work020' AND sort_order = 1 AND image_key = 'images/works/work020/still2.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/003.webp' WHERE work_id = 'work020' AND sort_order = 2 AND image_key = 'images/works/work020/still3.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/004.webp' WHERE work_id = 'work020' AND sort_order = 3 AND image_key = 'images/works/work020/still4.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/005.webp' WHERE work_id = 'work020' AND sort_order = 4 AND image_key = 'images/works/work020/still5.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/006.webp' WHERE work_id = 'work020' AND sort_order = 5 AND image_key = 'images/works/work020/still6.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/007.webp' WHERE work_id = 'work020' AND sort_order = 6 AND image_key = 'images/works/work020/still7.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/008.webp' WHERE work_id = 'work020' AND sort_order = 7 AND image_key = 'images/works/work020/still8.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/009.webp' WHERE work_id = 'work020' AND sort_order = 8 AND image_key = 'images/works/work020/still9.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/010.webp' WHERE work_id = 'work020' AND sort_order = 9 AND image_key = 'images/works/work020/still10.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/011.webp' WHERE work_id = 'work020' AND sort_order = 10 AND image_key = 'images/works/work020/still11.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/012.webp' WHERE work_id = 'work020' AND sort_order = 11 AND image_key = 'images/works/work020/still12.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/013.webp' WHERE work_id = 'work020' AND sort_order = 12 AND image_key = 'images/works/work020/still13.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/014.webp' WHERE work_id = 'work020' AND sort_order = 13 AND image_key = 'images/works/work020/still14.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/015.webp' WHERE work_id = 'work020' AND sort_order = 14 AND image_key = 'images/works/work020/still15.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/016.webp' WHERE work_id = 'work020' AND sort_order = 15 AND image_key = 'images/works/work020/still16.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/017.webp' WHERE work_id = 'work020' AND sort_order = 16 AND image_key = 'images/works/work020/still17.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/018.webp' WHERE work_id = 'work020' AND sort_order = 17 AND image_key = 'images/works/work020/still18.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/019.webp' WHERE work_id = 'work020' AND sort_order = 18 AND image_key = 'images/works/work020/still19.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/020.webp' WHERE work_id = 'work020' AND sort_order = 19 AND image_key = 'images/works/work020/still20.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/021.webp' WHERE work_id = 'work020' AND sort_order = 20 AND image_key = 'images/works/work020/still21.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/022.webp' WHERE work_id = 'work020' AND sort_order = 21 AND image_key = 'images/works/work020/still22.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/023.webp' WHERE work_id = 'work020' AND sort_order = 22 AND image_key = 'images/works/work020/still23.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/024.webp' WHERE work_id = 'work020' AND sort_order = 23 AND image_key = 'images/works/work020/still24.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/025.webp' WHERE work_id = 'work020' AND sort_order = 24 AND image_key = 'images/works/work020/still25.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/026.webp' WHERE work_id = 'work020' AND sort_order = 25 AND image_key = 'images/works/work020/still26.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/027.webp' WHERE work_id = 'work020' AND sort_order = 26 AND image_key = 'images/works/work020/still27.jpg';
UPDATE work_images SET image_key = 'works/work020/stills/028.webp' WHERE work_id = 'work020' AND sort_order = 27 AND image_key = 'images/works/work020/still28.jpg';
UPDATE works SET thumbnail_key = 'works/work019/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work019' AND thumbnail_key = 'images/works/work019/thumb.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/001.webp' WHERE work_id = 'work019' AND sort_order = 0 AND image_key = 'images/works/work019/still1.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/002.webp' WHERE work_id = 'work019' AND sort_order = 1 AND image_key = 'images/works/work019/still2.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/003.webp' WHERE work_id = 'work019' AND sort_order = 2 AND image_key = 'images/works/work019/still3.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/004.webp' WHERE work_id = 'work019' AND sort_order = 3 AND image_key = 'images/works/work019/still4.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/005.webp' WHERE work_id = 'work019' AND sort_order = 4 AND image_key = 'images/works/work019/still5.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/006.webp' WHERE work_id = 'work019' AND sort_order = 5 AND image_key = 'images/works/work019/still6.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/007.webp' WHERE work_id = 'work019' AND sort_order = 6 AND image_key = 'images/works/work019/still7.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/008.webp' WHERE work_id = 'work019' AND sort_order = 7 AND image_key = 'images/works/work019/still8.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/009.webp' WHERE work_id = 'work019' AND sort_order = 8 AND image_key = 'images/works/work019/still9.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/010.webp' WHERE work_id = 'work019' AND sort_order = 9 AND image_key = 'images/works/work019/still10.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/011.webp' WHERE work_id = 'work019' AND sort_order = 10 AND image_key = 'images/works/work019/still11.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/013.webp' WHERE work_id = 'work019' AND sort_order = 12 AND image_key = 'images/works/work019/still13.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/014.webp' WHERE work_id = 'work019' AND sort_order = 13 AND image_key = 'images/works/work019/still14.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/015.webp' WHERE work_id = 'work019' AND sort_order = 14 AND image_key = 'images/works/work019/still15.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/016.webp' WHERE work_id = 'work019' AND sort_order = 15 AND image_key = 'images/works/work019/still16.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/017.webp' WHERE work_id = 'work019' AND sort_order = 16 AND image_key = 'images/works/work019/still17.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/018.webp' WHERE work_id = 'work019' AND sort_order = 17 AND image_key = 'images/works/work019/still18.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/019.webp' WHERE work_id = 'work019' AND sort_order = 18 AND image_key = 'images/works/work019/still19.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/020.webp' WHERE work_id = 'work019' AND sort_order = 19 AND image_key = 'images/works/work019/still20.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/021.webp' WHERE work_id = 'work019' AND sort_order = 20 AND image_key = 'images/works/work019/still21.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/022.webp' WHERE work_id = 'work019' AND sort_order = 21 AND image_key = 'images/works/work019/still22.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/023.webp' WHERE work_id = 'work019' AND sort_order = 22 AND image_key = 'images/works/work019/still23.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/024.webp' WHERE work_id = 'work019' AND sort_order = 23 AND image_key = 'images/works/work019/still24.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/025.webp' WHERE work_id = 'work019' AND sort_order = 24 AND image_key = 'images/works/work019/still25.jpeg';
UPDATE work_images SET image_key = 'works/work019/stills/026.webp' WHERE work_id = 'work019' AND sort_order = 25 AND image_key = 'images/works/work019/still26.jpeg';
UPDATE works SET thumbnail_key = 'works/work017/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work017' AND thumbnail_key = 'images/works/work017/thumb.jpeg';
UPDATE work_images SET image_key = 'works/work017/stills/001.webp' WHERE work_id = 'work017' AND sort_order = 0 AND image_key = 'images/works/work017/still1.jpeg';
UPDATE work_images SET image_key = 'works/work017/stills/002.webp' WHERE work_id = 'work017' AND sort_order = 1 AND image_key = 'images/works/work017/still2.jpeg';
UPDATE work_images SET image_key = 'works/work017/stills/003.webp' WHERE work_id = 'work017' AND sort_order = 2 AND image_key = 'images/works/work017/still3.jpeg';
UPDATE work_images SET image_key = 'works/work017/stills/004.webp' WHERE work_id = 'work017' AND sort_order = 3 AND image_key = 'images/works/work017/still4.jpeg';
UPDATE work_images SET image_key = 'works/work017/stills/005.webp' WHERE work_id = 'work017' AND sort_order = 4 AND image_key = 'images/works/work017/still5.jpeg';
UPDATE work_images SET image_key = 'works/work017/stills/006.webp' WHERE work_id = 'work017' AND sort_order = 5 AND image_key = 'images/works/work017/still6.jpeg';
UPDATE work_images SET image_key = 'works/work017/stills/007.webp' WHERE work_id = 'work017' AND sort_order = 6 AND image_key = 'images/works/work017/still7.jpeg';
UPDATE work_images SET image_key = 'works/work017/stills/008.webp' WHERE work_id = 'work017' AND sort_order = 7 AND image_key = 'images/works/work017/still8.jpeg';
UPDATE work_images SET image_key = 'works/work017/stills/009.webp' WHERE work_id = 'work017' AND sort_order = 8 AND image_key = 'images/works/work017/still9.jpeg';
UPDATE work_images SET image_key = 'works/work017/stills/010.webp' WHERE work_id = 'work017' AND sort_order = 9 AND image_key = 'images/works/work017/still10.jpeg';
UPDATE work_images SET image_key = 'works/work017/stills/011.webp' WHERE work_id = 'work017' AND sort_order = 10 AND image_key = 'images/works/work017/still11.jpeg';
UPDATE work_images SET image_key = 'works/work017/stills/012.webp' WHERE work_id = 'work017' AND sort_order = 11 AND image_key = 'images/works/work017/still12.jpeg';
UPDATE work_images SET image_key = 'works/work017/stills/013.webp' WHERE work_id = 'work017' AND sort_order = 12 AND image_key = 'images/works/work017/still13.jpeg';
UPDATE works SET thumbnail_key = 'works/work016/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work016' AND thumbnail_key = 'images/works/work016/thumb.jpeg';
UPDATE work_images SET image_key = 'works/work016/stills/001.webp' WHERE work_id = 'work016' AND sort_order = 0 AND image_key = 'images/works/work016/still1.jpeg';
UPDATE work_images SET image_key = 'works/work016/stills/002.webp' WHERE work_id = 'work016' AND sort_order = 1 AND image_key = 'images/works/work016/still2.jpeg';
UPDATE work_images SET image_key = 'works/work016/stills/003.webp' WHERE work_id = 'work016' AND sort_order = 2 AND image_key = 'images/works/work016/still3.jpeg';
UPDATE work_images SET image_key = 'works/work016/stills/004.webp' WHERE work_id = 'work016' AND sort_order = 3 AND image_key = 'images/works/work016/still4.jpeg';
UPDATE work_images SET image_key = 'works/work016/stills/005.webp' WHERE work_id = 'work016' AND sort_order = 4 AND image_key = 'images/works/work016/still5.jpeg';
UPDATE work_images SET image_key = 'works/work016/stills/006.webp' WHERE work_id = 'work016' AND sort_order = 5 AND image_key = 'images/works/work016/still6.jpeg';
UPDATE work_images SET image_key = 'works/work016/stills/007.webp' WHERE work_id = 'work016' AND sort_order = 6 AND image_key = 'images/works/work016/still7.jpeg';
UPDATE work_images SET image_key = 'works/work016/stills/008.webp' WHERE work_id = 'work016' AND sort_order = 7 AND image_key = 'images/works/work016/still8.jpeg';
UPDATE work_images SET image_key = 'works/work016/stills/009.webp' WHERE work_id = 'work016' AND sort_order = 8 AND image_key = 'images/works/work016/still9.jpeg';
UPDATE work_images SET image_key = 'works/work016/stills/010.webp' WHERE work_id = 'work016' AND sort_order = 9 AND image_key = 'images/works/work016/still10.jpeg';
UPDATE work_images SET image_key = 'works/work016/stills/011.webp' WHERE work_id = 'work016' AND sort_order = 10 AND image_key = 'images/works/work016/still11.jpeg';
UPDATE work_images SET image_key = 'works/work016/stills/012.webp' WHERE work_id = 'work016' AND sort_order = 11 AND image_key = 'images/works/work016/still12.jpeg';
UPDATE work_images SET image_key = 'works/work016/stills/013.webp' WHERE work_id = 'work016' AND sort_order = 12 AND image_key = 'images/works/work016/still13.jpeg';
UPDATE work_images SET image_key = 'works/work016/stills/014.webp' WHERE work_id = 'work016' AND sort_order = 13 AND image_key = 'images/works/work016/still14.jpeg';
UPDATE work_images SET image_key = 'works/work016/stills/015.webp' WHERE work_id = 'work016' AND sort_order = 14 AND image_key = 'images/works/work016/still15.jpeg';
UPDATE works SET thumbnail_key = 'works/work015/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work015' AND thumbnail_key = 'images/works/work015/thumb.png';
UPDATE work_images SET image_key = 'works/work015/stills/001.webp' WHERE work_id = 'work015' AND sort_order = 0 AND image_key = 'images/works/work015/still1.png';
UPDATE work_images SET image_key = 'works/work015/stills/002.webp' WHERE work_id = 'work015' AND sort_order = 1 AND image_key = 'images/works/work015/still2.png';
UPDATE work_images SET image_key = 'works/work015/stills/003.webp' WHERE work_id = 'work015' AND sort_order = 2 AND image_key = 'images/works/work015/still3.png';
UPDATE work_images SET image_key = 'works/work015/stills/004.webp' WHERE work_id = 'work015' AND sort_order = 3 AND image_key = 'images/works/work015/still4.png';
UPDATE work_images SET image_key = 'works/work015/stills/005.webp' WHERE work_id = 'work015' AND sort_order = 4 AND image_key = 'images/works/work015/still5.png';
UPDATE work_images SET image_key = 'works/work015/stills/006.webp' WHERE work_id = 'work015' AND sort_order = 5 AND image_key = 'images/works/work015/still6.png';
UPDATE work_images SET image_key = 'works/work015/stills/007.webp' WHERE work_id = 'work015' AND sort_order = 6 AND image_key = 'images/works/work015/still7.png';
UPDATE work_images SET image_key = 'works/work015/stills/008.webp' WHERE work_id = 'work015' AND sort_order = 7 AND image_key = 'images/works/work015/still8.png';
UPDATE work_images SET image_key = 'works/work015/stills/009.webp' WHERE work_id = 'work015' AND sort_order = 8 AND image_key = 'images/works/work015/still9.png';
UPDATE works SET thumbnail_key = 'works/work013/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work013' AND thumbnail_key = 'images/works/work013/thumb.jpg';
UPDATE work_images SET image_key = 'works/work013/stills/001.webp' WHERE work_id = 'work013' AND sort_order = 0 AND image_key = 'images/works/work013/still1.jpg';
UPDATE work_images SET image_key = 'works/work013/stills/002.webp' WHERE work_id = 'work013' AND sort_order = 1 AND image_key = 'images/works/work013/still2.jpg';
UPDATE work_images SET image_key = 'works/work013/stills/003.webp' WHERE work_id = 'work013' AND sort_order = 2 AND image_key = 'images/works/work013/still3.jpg';
UPDATE work_images SET image_key = 'works/work013/stills/004.webp' WHERE work_id = 'work013' AND sort_order = 3 AND image_key = 'images/works/work013/still4.jpg';
UPDATE work_images SET image_key = 'works/work013/stills/005.webp' WHERE work_id = 'work013' AND sort_order = 4 AND image_key = 'images/works/work013/still5.jpg';
UPDATE work_images SET image_key = 'works/work013/stills/006.webp' WHERE work_id = 'work013' AND sort_order = 5 AND image_key = 'images/works/work013/still6.jpg';
UPDATE work_images SET image_key = 'works/work013/stills/007.webp' WHERE work_id = 'work013' AND sort_order = 6 AND image_key = 'images/works/work013/still7.jpg';
UPDATE work_images SET image_key = 'works/work013/stills/008.webp' WHERE work_id = 'work013' AND sort_order = 7 AND image_key = 'images/works/work013/still8.jpg';
UPDATE work_images SET image_key = 'works/work013/stills/009.webp' WHERE work_id = 'work013' AND sort_order = 8 AND image_key = 'images/works/work013/still9.jpg';
UPDATE works SET thumbnail_key = 'works/work014/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work014' AND thumbnail_key = 'images/works/work014/thumb.jpg';
UPDATE work_images SET image_key = 'works/work014/stills/001.webp' WHERE work_id = 'work014' AND sort_order = 0 AND image_key = 'images/works/work014/still1.jpeg';
UPDATE work_images SET image_key = 'works/work014/stills/002.webp' WHERE work_id = 'work014' AND sort_order = 1 AND image_key = 'images/works/work014/still2.jpeg';
UPDATE work_images SET image_key = 'works/work014/stills/003.webp' WHERE work_id = 'work014' AND sort_order = 2 AND image_key = 'images/works/work014/still3.jpeg';
UPDATE work_images SET image_key = 'works/work014/stills/004.webp' WHERE work_id = 'work014' AND sort_order = 3 AND image_key = 'images/works/work014/still4.jpeg';
UPDATE work_images SET image_key = 'works/work014/stills/005.webp' WHERE work_id = 'work014' AND sort_order = 4 AND image_key = 'images/works/work014/still5.jpeg';
UPDATE work_images SET image_key = 'works/work014/stills/006.webp' WHERE work_id = 'work014' AND sort_order = 5 AND image_key = 'images/works/work014/still6.jpeg';
UPDATE work_images SET image_key = 'works/work014/stills/007.webp' WHERE work_id = 'work014' AND sort_order = 6 AND image_key = 'images/works/work014/still7.jpeg';
UPDATE work_images SET image_key = 'works/work014/stills/008.webp' WHERE work_id = 'work014' AND sort_order = 7 AND image_key = 'images/works/work014/still8.jpeg';
UPDATE work_images SET image_key = 'works/work014/stills/009.webp' WHERE work_id = 'work014' AND sort_order = 8 AND image_key = 'images/works/work014/still9.jpeg';
UPDATE work_images SET image_key = 'works/work014/stills/010.webp' WHERE work_id = 'work014' AND sort_order = 9 AND image_key = 'images/works/work014/still10.jpeg';
UPDATE work_images SET image_key = 'works/work014/stills/011.webp' WHERE work_id = 'work014' AND sort_order = 10 AND image_key = 'images/works/work014/still11.jpeg';
UPDATE works SET thumbnail_key = 'works/work012/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work012' AND thumbnail_key = 'images/works/work012/thumb.jpg';
UPDATE work_images SET image_key = 'works/work012/stills/001.webp' WHERE work_id = 'work012' AND sort_order = 0 AND image_key = 'images/works/work012/still1.jpg';
UPDATE work_images SET image_key = 'works/work012/stills/002.webp' WHERE work_id = 'work012' AND sort_order = 1 AND image_key = 'images/works/work012/still2.jpg';
UPDATE work_images SET image_key = 'works/work012/stills/003.webp' WHERE work_id = 'work012' AND sort_order = 2 AND image_key = 'images/works/work012/still3.jpg';
UPDATE work_images SET image_key = 'works/work012/stills/004.webp' WHERE work_id = 'work012' AND sort_order = 3 AND image_key = 'images/works/work012/still4.jpg';
UPDATE work_images SET image_key = 'works/work012/stills/005.webp' WHERE work_id = 'work012' AND sort_order = 4 AND image_key = 'images/works/work012/still5.jpg';
UPDATE work_images SET image_key = 'works/work012/stills/006.webp' WHERE work_id = 'work012' AND sort_order = 5 AND image_key = 'images/works/work012/still6.jpg';
UPDATE work_images SET image_key = 'works/work012/stills/007.webp' WHERE work_id = 'work012' AND sort_order = 6 AND image_key = 'images/works/work012/still7.jpg';
UPDATE work_images SET image_key = 'works/work012/stills/008.webp' WHERE work_id = 'work012' AND sort_order = 7 AND image_key = 'images/works/work012/still8.jpg';
UPDATE work_images SET image_key = 'works/work012/stills/009.webp' WHERE work_id = 'work012' AND sort_order = 8 AND image_key = 'images/works/work012/still9.jpg';
UPDATE work_images SET image_key = 'works/work012/stills/010.webp' WHERE work_id = 'work012' AND sort_order = 9 AND image_key = 'images/works/work012/still10.jpg';
UPDATE work_images SET image_key = 'works/work012/stills/011.webp' WHERE work_id = 'work012' AND sort_order = 10 AND image_key = 'images/works/work012/still11.jpg';
UPDATE work_images SET image_key = 'works/work012/stills/012.webp' WHERE work_id = 'work012' AND sort_order = 11 AND image_key = 'images/works/work012/still12.jpg';
UPDATE work_images SET image_key = 'works/work012/stills/013.webp' WHERE work_id = 'work012' AND sort_order = 12 AND image_key = 'images/works/work012/still13.jpg';
UPDATE works SET thumbnail_key = 'works/work011/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work011' AND thumbnail_key = 'images/works/work011/thumb.png';
UPDATE work_images SET image_key = 'works/work011/stills/001.webp' WHERE work_id = 'work011' AND sort_order = 0 AND image_key = 'images/works/work011/still1.png';
UPDATE work_images SET image_key = 'works/work011/stills/002.webp' WHERE work_id = 'work011' AND sort_order = 1 AND image_key = 'images/works/work011/still2.png';
UPDATE work_images SET image_key = 'works/work011/stills/003.webp' WHERE work_id = 'work011' AND sort_order = 2 AND image_key = 'images/works/work011/still3.png';
UPDATE work_images SET image_key = 'works/work011/stills/004.webp' WHERE work_id = 'work011' AND sort_order = 3 AND image_key = 'images/works/work011/still4.png';
UPDATE work_images SET image_key = 'works/work011/stills/005.webp' WHERE work_id = 'work011' AND sort_order = 4 AND image_key = 'images/works/work011/still5.png';
UPDATE work_images SET image_key = 'works/work011/stills/006.webp' WHERE work_id = 'work011' AND sort_order = 5 AND image_key = 'images/works/work011/still6.png';
UPDATE work_images SET image_key = 'works/work011/stills/007.webp' WHERE work_id = 'work011' AND sort_order = 6 AND image_key = 'images/works/work011/still7.png';
UPDATE work_images SET image_key = 'works/work011/stills/008.webp' WHERE work_id = 'work011' AND sort_order = 7 AND image_key = 'images/works/work011/still8.png';
UPDATE work_images SET image_key = 'works/work011/stills/009.webp' WHERE work_id = 'work011' AND sort_order = 8 AND image_key = 'images/works/work011/still9.png';
UPDATE work_images SET image_key = 'works/work011/stills/010.webp' WHERE work_id = 'work011' AND sort_order = 9 AND image_key = 'images/works/work011/still10.png';
UPDATE work_images SET image_key = 'works/work011/stills/011.webp' WHERE work_id = 'work011' AND sort_order = 10 AND image_key = 'images/works/work011/still11.png';
UPDATE works SET thumbnail_key = 'works/work010/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work010' AND thumbnail_key = 'images/works/work010/thumb.png';
UPDATE work_images SET image_key = 'works/work010/stills/001.webp' WHERE work_id = 'work010' AND sort_order = 0 AND image_key = 'images/works/work010/still1.jpeg';
UPDATE work_images SET image_key = 'works/work010/stills/002.webp' WHERE work_id = 'work010' AND sort_order = 1 AND image_key = 'images/works/work010/still2.jpeg';
UPDATE work_images SET image_key = 'works/work010/stills/003.webp' WHERE work_id = 'work010' AND sort_order = 2 AND image_key = 'images/works/work010/still3.jpeg';
UPDATE work_images SET image_key = 'works/work010/stills/004.webp' WHERE work_id = 'work010' AND sort_order = 3 AND image_key = 'images/works/work010/still4.jpeg';
UPDATE work_images SET image_key = 'works/work010/stills/005.webp' WHERE work_id = 'work010' AND sort_order = 4 AND image_key = 'images/works/work010/still5.jpeg';
UPDATE work_images SET image_key = 'works/work010/stills/006.webp' WHERE work_id = 'work010' AND sort_order = 5 AND image_key = 'images/works/work010/still6.jpeg';
UPDATE work_images SET image_key = 'works/work010/stills/007.webp' WHERE work_id = 'work010' AND sort_order = 6 AND image_key = 'images/works/work010/still7.jpeg';
UPDATE work_images SET image_key = 'works/work010/stills/008.webp' WHERE work_id = 'work010' AND sort_order = 7 AND image_key = 'images/works/work010/still8.jpeg';
UPDATE work_images SET image_key = 'works/work010/stills/009.webp' WHERE work_id = 'work010' AND sort_order = 8 AND image_key = 'images/works/work010/still9.jpeg';
UPDATE work_images SET image_key = 'works/work010/stills/010.webp' WHERE work_id = 'work010' AND sort_order = 9 AND image_key = 'images/works/work010/still10.jpeg';
UPDATE work_images SET image_key = 'works/work010/stills/011.webp' WHERE work_id = 'work010' AND sort_order = 10 AND image_key = 'images/works/work010/still11.jpeg';
UPDATE work_images SET image_key = 'works/work010/stills/012.webp' WHERE work_id = 'work010' AND sort_order = 11 AND image_key = 'images/works/work010/still12.jpeg';
UPDATE work_images SET image_key = 'works/work010/stills/013.webp' WHERE work_id = 'work010' AND sort_order = 12 AND image_key = 'images/works/work010/still13.jpeg';
UPDATE work_images SET image_key = 'works/work010/stills/014.webp' WHERE work_id = 'work010' AND sort_order = 13 AND image_key = 'images/works/work010/still14.jpeg';
UPDATE work_images SET image_key = 'works/work010/stills/015.webp' WHERE work_id = 'work010' AND sort_order = 14 AND image_key = 'images/works/work010/still15.jpeg';
UPDATE works SET thumbnail_key = 'works/work009/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work009' AND thumbnail_key = 'images/works/work009/thumb.png';
UPDATE work_images SET image_key = 'works/work009/stills/001.webp' WHERE work_id = 'work009' AND sort_order = 0 AND image_key = 'images/works/work009/still1.jpeg';
UPDATE work_images SET image_key = 'works/work009/stills/002.webp' WHERE work_id = 'work009' AND sort_order = 1 AND image_key = 'images/works/work009/still2.jpeg';
UPDATE work_images SET image_key = 'works/work009/stills/003.webp' WHERE work_id = 'work009' AND sort_order = 2 AND image_key = 'images/works/work009/still3.jpeg';
UPDATE work_images SET image_key = 'works/work009/stills/004.webp' WHERE work_id = 'work009' AND sort_order = 3 AND image_key = 'images/works/work009/still4.jpeg';
UPDATE work_images SET image_key = 'works/work009/stills/005.webp' WHERE work_id = 'work009' AND sort_order = 4 AND image_key = 'images/works/work009/still5.jpeg';
UPDATE work_images SET image_key = 'works/work009/stills/006.webp' WHERE work_id = 'work009' AND sort_order = 5 AND image_key = 'images/works/work009/still6.jpeg';
UPDATE work_images SET image_key = 'works/work009/stills/007.webp' WHERE work_id = 'work009' AND sort_order = 6 AND image_key = 'images/works/work009/still7.jpeg';
UPDATE work_images SET image_key = 'works/work009/stills/008.webp' WHERE work_id = 'work009' AND sort_order = 7 AND image_key = 'images/works/work009/still8.jpeg';
UPDATE work_images SET image_key = 'works/work009/stills/009.webp' WHERE work_id = 'work009' AND sort_order = 8 AND image_key = 'images/works/work009/still9.jpeg';
UPDATE work_images SET image_key = 'works/work009/stills/010.webp' WHERE work_id = 'work009' AND sort_order = 9 AND image_key = 'images/works/work009/still10.jpeg';
UPDATE work_images SET image_key = 'works/work009/stills/011.webp' WHERE work_id = 'work009' AND sort_order = 10 AND image_key = 'images/works/work009/still11.jpeg';
UPDATE work_images SET image_key = 'works/work009/stills/012.webp' WHERE work_id = 'work009' AND sort_order = 11 AND image_key = 'images/works/work009/still12.jpeg';
UPDATE work_images SET image_key = 'works/work009/stills/013.webp' WHERE work_id = 'work009' AND sort_order = 12 AND image_key = 'images/works/work009/still13.jpeg';
UPDATE works SET thumbnail_key = 'works/work008/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work008' AND thumbnail_key = 'images/works/work008/thumb.png';
UPDATE work_images SET image_key = 'works/work008/stills/001.webp' WHERE work_id = 'work008' AND sort_order = 0 AND image_key = 'images/works/work008/still1.jpeg';
UPDATE work_images SET image_key = 'works/work008/stills/002.webp' WHERE work_id = 'work008' AND sort_order = 1 AND image_key = 'images/works/work008/still2.jpeg';
UPDATE work_images SET image_key = 'works/work008/stills/003.webp' WHERE work_id = 'work008' AND sort_order = 2 AND image_key = 'images/works/work008/still3.jpeg';
UPDATE work_images SET image_key = 'works/work008/stills/004.webp' WHERE work_id = 'work008' AND sort_order = 3 AND image_key = 'images/works/work008/still4.jpeg';
UPDATE work_images SET image_key = 'works/work008/stills/005.webp' WHERE work_id = 'work008' AND sort_order = 4 AND image_key = 'images/works/work008/still5.jpeg';
UPDATE work_images SET image_key = 'works/work008/stills/006.webp' WHERE work_id = 'work008' AND sort_order = 5 AND image_key = 'images/works/work008/still6.jpeg';
UPDATE work_images SET image_key = 'works/work008/stills/007.webp' WHERE work_id = 'work008' AND sort_order = 6 AND image_key = 'images/works/work008/still7.jpeg';
UPDATE work_images SET image_key = 'works/work008/stills/008.webp' WHERE work_id = 'work008' AND sort_order = 7 AND image_key = 'images/works/work008/still8.jpeg';
UPDATE work_images SET image_key = 'works/work008/stills/009.webp' WHERE work_id = 'work008' AND sort_order = 8 AND image_key = 'images/works/work008/still9.jpeg';
UPDATE work_images SET image_key = 'works/work008/stills/010.webp' WHERE work_id = 'work008' AND sort_order = 9 AND image_key = 'images/works/work008/still10.jpeg';
UPDATE work_images SET image_key = 'works/work008/stills/011.webp' WHERE work_id = 'work008' AND sort_order = 10 AND image_key = 'images/works/work008/still11.jpeg';
UPDATE work_images SET image_key = 'works/work008/stills/012.webp' WHERE work_id = 'work008' AND sort_order = 11 AND image_key = 'images/works/work008/still12.jpeg';
UPDATE work_images SET image_key = 'works/work008/stills/013.webp' WHERE work_id = 'work008' AND sort_order = 12 AND image_key = 'images/works/work008/still13.jpeg';
UPDATE works SET thumbnail_key = 'works/work007/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work007' AND thumbnail_key = 'images/works/work007/thumb.png';
UPDATE work_images SET image_key = 'works/work007/stills/001.webp' WHERE work_id = 'work007' AND sort_order = 0 AND image_key = 'images/works/work007/still1.jpeg';
UPDATE work_images SET image_key = 'works/work007/stills/002.webp' WHERE work_id = 'work007' AND sort_order = 1 AND image_key = 'images/works/work007/still2.jpeg';
UPDATE work_images SET image_key = 'works/work007/stills/003.webp' WHERE work_id = 'work007' AND sort_order = 2 AND image_key = 'images/works/work007/still3.jpeg';
UPDATE work_images SET image_key = 'works/work007/stills/004.webp' WHERE work_id = 'work007' AND sort_order = 3 AND image_key = 'images/works/work007/still4.jpeg';
UPDATE work_images SET image_key = 'works/work007/stills/005.webp' WHERE work_id = 'work007' AND sort_order = 4 AND image_key = 'images/works/work007/still5.jpeg';
UPDATE work_images SET image_key = 'works/work007/stills/006.webp' WHERE work_id = 'work007' AND sort_order = 5 AND image_key = 'images/works/work007/still6.jpeg';
UPDATE work_images SET image_key = 'works/work007/stills/007.webp' WHERE work_id = 'work007' AND sort_order = 6 AND image_key = 'images/works/work007/still7.jpeg';
UPDATE work_images SET image_key = 'works/work007/stills/008.webp' WHERE work_id = 'work007' AND sort_order = 7 AND image_key = 'images/works/work007/still8.jpeg';
UPDATE work_images SET image_key = 'works/work007/stills/009.webp' WHERE work_id = 'work007' AND sort_order = 8 AND image_key = 'images/works/work007/still9.jpeg';
UPDATE work_images SET image_key = 'works/work007/stills/010.webp' WHERE work_id = 'work007' AND sort_order = 9 AND image_key = 'images/works/work007/still10.jpeg';
UPDATE work_images SET image_key = 'works/work007/stills/011.webp' WHERE work_id = 'work007' AND sort_order = 10 AND image_key = 'images/works/work007/still11.jpeg';
UPDATE work_images SET image_key = 'works/work007/stills/012.webp' WHERE work_id = 'work007' AND sort_order = 11 AND image_key = 'images/works/work007/still12.jpeg';
UPDATE works SET thumbnail_key = 'works/work006/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work006' AND thumbnail_key = 'images/works/work006/thumb.png';
UPDATE works SET thumbnail_key = 'works/work004/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work004' AND thumbnail_key = 'images/works/work004/thumb.png';
UPDATE works SET thumbnail_key = 'works/work003/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work003' AND thumbnail_key = 'images/works/work003/thumb.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/001.webp' WHERE work_id = 'work003' AND sort_order = 0 AND image_key = 'images/works/work003/still1.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/002.webp' WHERE work_id = 'work003' AND sort_order = 1 AND image_key = 'images/works/work003/still2.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/003.webp' WHERE work_id = 'work003' AND sort_order = 2 AND image_key = 'images/works/work003/still3.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/004.webp' WHERE work_id = 'work003' AND sort_order = 3 AND image_key = 'images/works/work003/still4.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/005.webp' WHERE work_id = 'work003' AND sort_order = 4 AND image_key = 'images/works/work003/still5.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/006.webp' WHERE work_id = 'work003' AND sort_order = 5 AND image_key = 'images/works/work003/still6.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/007.webp' WHERE work_id = 'work003' AND sort_order = 6 AND image_key = 'images/works/work003/still7.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/008.webp' WHERE work_id = 'work003' AND sort_order = 7 AND image_key = 'images/works/work003/still8.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/009.webp' WHERE work_id = 'work003' AND sort_order = 8 AND image_key = 'images/works/work003/still9.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/010.webp' WHERE work_id = 'work003' AND sort_order = 9 AND image_key = 'images/works/work003/still10.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/011.webp' WHERE work_id = 'work003' AND sort_order = 10 AND image_key = 'images/works/work003/still11.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/012.webp' WHERE work_id = 'work003' AND sort_order = 11 AND image_key = 'images/works/work003/still12.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/013.webp' WHERE work_id = 'work003' AND sort_order = 12 AND image_key = 'images/works/work003/still13.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/014.webp' WHERE work_id = 'work003' AND sort_order = 13 AND image_key = 'images/works/work003/still14.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/015.webp' WHERE work_id = 'work003' AND sort_order = 14 AND image_key = 'images/works/work003/still15.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/016.webp' WHERE work_id = 'work003' AND sort_order = 15 AND image_key = 'images/works/work003/still16.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/017.webp' WHERE work_id = 'work003' AND sort_order = 16 AND image_key = 'images/works/work003/still17.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/018.webp' WHERE work_id = 'work003' AND sort_order = 17 AND image_key = 'images/works/work003/still18.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/019.webp' WHERE work_id = 'work003' AND sort_order = 18 AND image_key = 'images/works/work003/still19.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/020.webp' WHERE work_id = 'work003' AND sort_order = 19 AND image_key = 'images/works/work003/still20.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/021.webp' WHERE work_id = 'work003' AND sort_order = 20 AND image_key = 'images/works/work003/still21.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/022.webp' WHERE work_id = 'work003' AND sort_order = 21 AND image_key = 'images/works/work003/still22.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/023.webp' WHERE work_id = 'work003' AND sort_order = 22 AND image_key = 'images/works/work003/still23.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/024.webp' WHERE work_id = 'work003' AND sort_order = 23 AND image_key = 'images/works/work003/still24.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/025.webp' WHERE work_id = 'work003' AND sort_order = 24 AND image_key = 'images/works/work003/still25.jpg';
UPDATE work_images SET image_key = 'works/work003/stills/026.webp' WHERE work_id = 'work003' AND sort_order = 25 AND image_key = 'images/works/work003/still26.jpg';
UPDATE works SET thumbnail_key = 'works/work002/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work002' AND thumbnail_key = 'images/works/work002/thumb.png';
UPDATE work_images SET image_key = 'works/work002/stills/001.webp' WHERE work_id = 'work002' AND sort_order = 0 AND image_key = 'images/works/work002/still1.jpeg';
UPDATE work_images SET image_key = 'works/work002/stills/002.webp' WHERE work_id = 'work002' AND sort_order = 1 AND image_key = 'images/works/work002/still2.jpeg';
UPDATE work_images SET image_key = 'works/work002/stills/003.webp' WHERE work_id = 'work002' AND sort_order = 2 AND image_key = 'images/works/work002/still3.jpeg';
UPDATE work_images SET image_key = 'works/work002/stills/004.webp' WHERE work_id = 'work002' AND sort_order = 3 AND image_key = 'images/works/work002/still4.jpeg';
UPDATE work_images SET image_key = 'works/work002/stills/005.webp' WHERE work_id = 'work002' AND sort_order = 4 AND image_key = 'images/works/work002/still5.jpeg';
UPDATE work_images SET image_key = 'works/work002/stills/006.webp' WHERE work_id = 'work002' AND sort_order = 5 AND image_key = 'images/works/work002/still6.jpeg';
UPDATE work_images SET image_key = 'works/work002/stills/007.webp' WHERE work_id = 'work002' AND sort_order = 6 AND image_key = 'images/works/work002/still7.jpeg';
UPDATE work_images SET image_key = 'works/work002/stills/008.webp' WHERE work_id = 'work002' AND sort_order = 7 AND image_key = 'images/works/work002/still8.jpeg';
UPDATE work_images SET image_key = 'works/work002/stills/009.webp' WHERE work_id = 'work002' AND sort_order = 8 AND image_key = 'images/works/work002/still9.jpeg';
UPDATE work_images SET image_key = 'works/work002/stills/010.webp' WHERE work_id = 'work002' AND sort_order = 9 AND image_key = 'images/works/work002/still10.jpeg';
UPDATE work_images SET image_key = 'works/work002/stills/011.webp' WHERE work_id = 'work002' AND sort_order = 10 AND image_key = 'images/works/work002/still11.jpeg';
UPDATE work_images SET image_key = 'works/work002/stills/012.webp' WHERE work_id = 'work002' AND sort_order = 11 AND image_key = 'images/works/work002/still12.jpeg';
UPDATE work_images SET image_key = 'works/work002/stills/013.webp' WHERE work_id = 'work002' AND sort_order = 12 AND image_key = 'images/works/work002/still13.jpeg';
UPDATE work_images SET image_key = 'works/work002/stills/014.webp' WHERE work_id = 'work002' AND sort_order = 13 AND image_key = 'images/works/work002/still14.jpeg';
UPDATE work_images SET image_key = 'works/work002/stills/015.webp' WHERE work_id = 'work002' AND sort_order = 14 AND image_key = 'images/works/work002/still15.jpeg';
UPDATE work_images SET image_key = 'works/work002/stills/016.webp' WHERE work_id = 'work002' AND sort_order = 15 AND image_key = 'images/works/work002/still16.jpeg';
UPDATE work_images SET image_key = 'works/work002/stills/017.webp' WHERE work_id = 'work002' AND sort_order = 16 AND image_key = 'images/works/work002/still17.jpeg';
UPDATE work_images SET image_key = 'works/work002/stills/018.webp' WHERE work_id = 'work002' AND sort_order = 17 AND image_key = 'images/works/work002/still18.jpeg';
UPDATE works SET thumbnail_key = 'works/work005/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work005' AND thumbnail_key = 'images/works/work005/thumb.png';
UPDATE work_images SET image_key = 'works/work005/stills/001.webp' WHERE work_id = 'work005' AND sort_order = 0 AND image_key = 'images/works/work005/still1.jpeg';
UPDATE work_images SET image_key = 'works/work005/stills/002.webp' WHERE work_id = 'work005' AND sort_order = 1 AND image_key = 'images/works/work005/still2.jpeg';
UPDATE work_images SET image_key = 'works/work005/stills/003.webp' WHERE work_id = 'work005' AND sort_order = 2 AND image_key = 'images/works/work005/still3.jpeg';
UPDATE work_images SET image_key = 'works/work005/stills/004.webp' WHERE work_id = 'work005' AND sort_order = 3 AND image_key = 'images/works/work005/still4.jpeg';
UPDATE work_images SET image_key = 'works/work005/stills/005.webp' WHERE work_id = 'work005' AND sort_order = 4 AND image_key = 'images/works/work005/still5.jpeg';
UPDATE work_images SET image_key = 'works/work005/stills/006.webp' WHERE work_id = 'work005' AND sort_order = 5 AND image_key = 'images/works/work005/still6.jpeg';
UPDATE work_images SET image_key = 'works/work005/stills/007.webp' WHERE work_id = 'work005' AND sort_order = 6 AND image_key = 'images/works/work005/still7.jpeg';
UPDATE work_images SET image_key = 'works/work005/stills/008.webp' WHERE work_id = 'work005' AND sort_order = 7 AND image_key = 'images/works/work005/still8.jpeg';
UPDATE work_images SET image_key = 'works/work005/stills/009.webp' WHERE work_id = 'work005' AND sort_order = 8 AND image_key = 'images/works/work005/still9.jpeg';
UPDATE work_images SET image_key = 'works/work005/stills/010.webp' WHERE work_id = 'work005' AND sort_order = 9 AND image_key = 'images/works/work005/still10.jpeg';
UPDATE work_images SET image_key = 'works/work005/stills/011.webp' WHERE work_id = 'work005' AND sort_order = 10 AND image_key = 'images/works/work005/still11.jpeg';
UPDATE work_images SET image_key = 'works/work005/stills/012.webp' WHERE work_id = 'work005' AND sort_order = 11 AND image_key = 'images/works/work005/still12.jpeg';
UPDATE work_images SET image_key = 'works/work005/stills/013.webp' WHERE work_id = 'work005' AND sort_order = 12 AND image_key = 'images/works/work005/still13.jpeg';
UPDATE work_images SET image_key = 'works/work005/stills/014.webp' WHERE work_id = 'work005' AND sort_order = 13 AND image_key = 'images/works/work005/still14.jpeg';
UPDATE work_images SET image_key = 'works/work005/stills/015.webp' WHERE work_id = 'work005' AND sort_order = 14 AND image_key = 'images/works/work005/still15.jpeg';
UPDATE work_images SET image_key = 'works/work005/stills/016.webp' WHERE work_id = 'work005' AND sort_order = 15 AND image_key = 'images/works/work005/still16.jpeg';
UPDATE work_images SET image_key = 'works/work005/stills/017.webp' WHERE work_id = 'work005' AND sort_order = 16 AND image_key = 'images/works/work005/still17.jpeg';
UPDATE work_images SET image_key = 'works/work005/stills/018.webp' WHERE work_id = 'work005' AND sort_order = 17 AND image_key = 'images/works/work005/still18.jpeg';
UPDATE work_images SET image_key = 'works/work005/stills/019.webp' WHERE work_id = 'work005' AND sort_order = 18 AND image_key = 'images/works/work005/still19.jpeg';
UPDATE work_images SET image_key = 'works/work005/stills/020.webp' WHERE work_id = 'work005' AND sort_order = 19 AND image_key = 'images/works/work005/still20.jpeg';
UPDATE work_images SET image_key = 'works/work005/stills/021.webp' WHERE work_id = 'work005' AND sort_order = 20 AND image_key = 'images/works/work005/still21.jpeg';
UPDATE work_images SET image_key = 'works/work005/stills/022.webp' WHERE work_id = 'work005' AND sort_order = 21 AND image_key = 'images/works/work005/still22.jpeg';
UPDATE works SET thumbnail_key = 'works/work001/thumb.webp', updated_at = CURRENT_TIMESTAMP WHERE id = 'work001' AND thumbnail_key = 'images/works/work001/thumb.jpg';
UPDATE work_images SET image_key = 'works/work001/stills/001.webp' WHERE work_id = 'work001' AND sort_order = 0 AND image_key = 'images/works/work001/still1.jpeg';
UPDATE work_images SET image_key = 'works/work001/stills/002.webp' WHERE work_id = 'work001' AND sort_order = 1 AND image_key = 'images/works/work001/still2.jpeg';
UPDATE work_images SET image_key = 'works/work001/stills/003.webp' WHERE work_id = 'work001' AND sort_order = 2 AND image_key = 'images/works/work001/still3.jpeg';
UPDATE work_images SET image_key = 'works/work001/stills/004.webp' WHERE work_id = 'work001' AND sort_order = 3 AND image_key = 'images/works/work001/still4.jpeg';
UPDATE work_images SET image_key = 'works/work001/stills/005.webp' WHERE work_id = 'work001' AND sort_order = 4 AND image_key = 'images/works/work001/still5.jpeg';
UPDATE work_images SET image_key = 'works/work001/stills/006.webp' WHERE work_id = 'work001' AND sort_order = 5 AND image_key = 'images/works/work001/still6.jpeg';
UPDATE work_images SET image_key = 'works/work001/stills/007.webp' WHERE work_id = 'work001' AND sort_order = 6 AND image_key = 'images/works/work001/still7.jpeg';
UPDATE work_images SET image_key = 'works/work001/stills/008.webp' WHERE work_id = 'work001' AND sort_order = 7 AND image_key = 'images/works/work001/still8.jpeg';
UPDATE work_images SET image_key = 'works/work001/stills/009.webp' WHERE work_id = 'work001' AND sort_order = 8 AND image_key = 'images/works/work001/still9.jpeg';
UPDATE work_images SET image_key = 'works/work001/stills/010.webp' WHERE work_id = 'work001' AND sort_order = 9 AND image_key = 'images/works/work001/still10.jpeg';
UPDATE work_images SET image_key = 'works/work001/stills/011.webp' WHERE work_id = 'work001' AND sort_order = 10 AND image_key = 'images/works/work001/still11.jpeg';
UPDATE work_images SET image_key = 'works/work001/stills/012.webp' WHERE work_id = 'work001' AND sort_order = 11 AND image_key = 'images/works/work001/still12.jpeg';
UPDATE work_images SET image_key = 'works/work001/stills/013.webp' WHERE work_id = 'work001' AND sort_order = 12 AND image_key = 'images/works/work001/still13.jpeg';
UPDATE work_images SET image_key = 'works/work001/stills/014.webp' WHERE work_id = 'work001' AND sort_order = 13 AND image_key = 'images/works/work001/still14.jpeg';
DELETE FROM work_images WHERE work_id = 'work018' AND image_key IN ('images/works/work018/still4.jpg', 'images/works/work018/still5.jpg');
DELETE FROM work_images WHERE work_id = 'work019' AND image_key = 'images/works/work019/still12.jpeg';


-- Compact still indexes for works that had broken legacy references.
DELETE FROM work_images WHERE work_id = 'work018';
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work018', 'works/work018/stills/001.webp', 0);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work018', 'works/work018/stills/002.webp', 1);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work018', 'works/work018/stills/003.webp', 2);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work018', 'works/work018/stills/004.webp', 3);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work018', 'works/work018/stills/005.webp', 4);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work018', 'works/work018/stills/006.webp', 5);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work018', 'works/work018/stills/007.webp', 6);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work018', 'works/work018/stills/008.webp', 7);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work018', 'works/work018/stills/009.webp', 8);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work018', 'works/work018/stills/010.webp', 9);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work018', 'works/work018/stills/011.webp', 10);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work018', 'works/work018/stills/012.webp', 11);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work018', 'works/work018/stills/013.webp', 12);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work018', 'works/work018/stills/014.webp', 13);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work018', 'works/work018/stills/015.webp', 14);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work018', 'works/work018/stills/016.webp', 15);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work018', 'works/work018/stills/017.webp', 16);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work018', 'works/work018/stills/018.webp', 17);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work018', 'works/work018/stills/019.webp', 18);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work018', 'works/work018/stills/020.webp', 19);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work018', 'works/work018/stills/021.webp', 20);
DELETE FROM work_images WHERE work_id = 'work019';
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/001.webp', 0);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/002.webp', 1);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/003.webp', 2);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/004.webp', 3);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/005.webp', 4);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/006.webp', 5);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/007.webp', 6);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/008.webp', 7);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/009.webp', 8);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/010.webp', 9);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/011.webp', 10);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/012.webp', 11);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/013.webp', 12);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/014.webp', 13);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/015.webp', 14);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/016.webp', 15);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/017.webp', 16);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/018.webp', 17);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/019.webp', 18);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/020.webp', 19);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/021.webp', 20);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/022.webp', 21);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/023.webp', 22);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/024.webp', 23);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/025.webp', 24);
INSERT INTO work_images (work_id, image_key, sort_order) VALUES ('work019', 'works/work019/stills/026.webp', 25);
